 language : python

dist: xenial

python:
    - "3.8"

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install: poetry install

script: make test

after_success:
  - pip install codecov
  - codecov
