language : python

dist: bionic

python:
    - "3.8"

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"
  - wget https://www.antlr.org/download/antlr-4.8-complete.jar

install: poetry install

before_script: make grammar

script: make test

after_success:
  - pip install codecov
  - codecov
