language : python

dist: xenial

python:
    - "3.8"

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"
  - wget https://www.antlr.org/download/antlr-4.8-complete.jar
  - java -jar antlr-4.8-complete.jar -o pywebidl2/generated -no-listener -visitor -Dlanguage=Python3  pywebidl2/WebIDLParser.g4 pywebidl2/WebIDLLexer.g4

install: poetry install

script: make test

after_success:
  - pip install codecov
  - codecov
