[tool.poetry]
name = "pywebidl2"
version = "0.1.3"
description = "WebIDL tool"
authors = ["Sergey Reshetnikov <resh.sersh@gmail.com>"]
license = "MIT"

readme = "README.md"
repository = "https://github.com/PrVrSs/pywebidl2"
homepage = "https://github.com/PrVrSs/pywebidl2"

keywords = [
  "WebIDL",
  "parser",
  "ast"
]

[tool.poetry.dependencies]
python = "^3.8"

antlr4-python3-runtime = "^4.8"
attrs = "^19.3.0"
click = "^7.1.2"
more-itertools = "^8.2.0"
stringcase = "^1.2.0"

[tool.poetry.dev-dependencies]
mypy = "^0.770"
pylint = "^2.5.2"
pytest = "^5.4.1"
pytest-cov = "^2.8.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
