[tool.poetry]
name = "pywebidl2"
version = "0.1.0"
description = "WebIDL tool"
authors = ["Sergey Reshetnikov <resh.sersh@gmail.com>"]
license = "MIT"

readme = "README.md"
repository = "https://github.com/PrVrSs/pywebidl2"
homepage = "https://github.com/PrVrSs/pywebidl2"

keywords = [
  "WebIDL",
  "parser",
  "ast"
]

[tool.poetry.dependencies]
python = "^3.8"
more-itertools = "^8.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
